export const aslImages = {
  a: require('../assets/signimages/a.png'),
  b: require('../assets/signimages/b.png'),
  c: require('../assets/signimages/c.png'),
  d: require('../assets/signimages/d.png'),
  e: require('../assets/signimages/e.png'),
  f: require('../assets/signimages/f.png'),
  g: require('../assets/signimages/g.png'),
  h: require('../assets/signimages/h.png'),
  i: require('../assets/signimages/i.png'),
  j: require('../assets/signimages/j.png'),
  k: require('../assets/signimages/k.png'),
  l: require('../assets/signimages/l.png'),
  m: require('../assets/signimages/m.png'),
  n: require('../assets/signimages/n.png'),
  o: require('../assets/signimages/o.png'),
  p: require('../assets/signimages/p.png'),
  q: require('../assets/signimages/q.png'),
  r: require('../assets/signimages/r.png'),
  s: require('../assets/signimages/s.png'),
  t: require('../assets/signimages/t.png'),
  u: require('../assets/signimages/u.png'),
  v: require('../assets/signimages/v.png'),
  w: require('../assets/signimages/w.png'),
  x: require('../assets/signimages/x.png'),
  y: require('../assets/signimages/y.png'),
  z: require('../assets/signimages/z.png'),
};
